x-producer-defaults: &producer-template
  build:
    context: ./producer
    dockerfile: Dockerfile
  volumes:
    - ./producer/producer.py:/app/producer.py
    - producer:/data
  depends_on:
    - kafka
  command: python3 /app/producer.py
  networks:
    - crypto_network
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 1g
        cpus: '0.5'
      reservations:
        memory: 512m
        cpus: '0.2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1g  # ou plus si tu as de la marge
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1g  # ou plus si tu as de la marge
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  kafka:
    image: confluentinc/cp-server:7.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1g  # ou plus si tu as de la marge
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  producer-1s:
    <<: *producer-template
    container_name: producer-1s
    environment:
      INTERVAL: 1s

  producer-1m:
    <<: *producer-template
    container_name: producer-1m
    environment:
      INTERVAL: 1m

  producer-15m:
    <<: *producer-template
    container_name: producer-15m
    environment:
      INTERVAL: 15m

  producer-1h:
    <<: *producer-template
    container_name: producer-1h
    environment:
      INTERVAL: 1h

  producer-1d:
    <<: *producer-template
    container_name: producer-1d
    environment:
      INTERVAL: 1d

networks:
  crypto_network:
    external: true

volumes:
  zookeeper_data:
    name: crypto_zookeeper_data
  kafka_data:
    name: crypto_kafka_data
  producer:
    name: crypto_producer
